const {
  REDIS_HOST,
  FIRE_HOUR = 10,
  FIRE_MINUTE = 15,
  FIRE_SECOND = 0,
  FIRE_MILLISECOND = 0,
  HOST_IP,
  HOST_SSH_PORT = 22,
  ID_RSA,
  ID_RSA_PUB,
  HOST_WORKDIR,
  HOST_USER,
  BUILD_LIST_EXPIRE_TIME = 48 * 3600,
} = process.env;

module.exports = {
  REDIS_HOST,
  FIRE_HOUR,
  FIRE_MINUTE,
  FIRE_SECOND,
  FIRE_MILLISECOND,
  HOST_IP,
  HOST_SSH_PORT,
  HOST_WORKDIR,
  ID_RSA,
  ID_RSA_PUB,
  HOST_USER,
  BUILD_LIST_EXPIRE_TIME,
};
